# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

# SEO settings
title: IncidentNormal
email: admin@incidentnormal.uk
description: > # this means to ignore newlines until "baseurl:"
  Blog / Proof of Concept deployment - a static website generated
  using Jekyll, and hosted on GitHub (with help from Cloudflare).

# Site settings
url: "https://incidentnormal.github.io"
baseurl: ""
# baseurl: ""

github_username: incidentnormal
